local palette = {}

palette.main = {
  gruber_darker_fg               = "#e4e4ef",
  gruber_darker_fg_1             = "#f4f4ff",
  gruber_darker_fg_2             = "#f5f5f5",
  gruber_darker_white            = "#ffffff",
  gruber_darker_black            = "#000000",
  gruber_darker_bg_m1            = "#101010",
  gruber_darker_bg               = "#181818",
  gruber_darker_bg_p1            = "#282828",
  gruber_darker_bg_p2            = "#453d41",
  gruber_darker_bg_p3            = "#484848",
  gruber_darker_bg_p4            = "#52494e",
  gruber_darker_red_m1           = "#c73c3f",
  gruber_darker_red              = "#f43841",
  gruber_darker_red_p1           = "#ff4f58",
  gruber_darker_green            = "#73c936",
  gruber_darker_yellow           = "#ffdd33",
  gruber_darker_brown            = "#cc8c3c",
  gruber_darker_quartz           = "#95a99f",
  gruber_darker_niagara_m2       = "#303540",
  gruber_darker_niagara_m1       = "#565f73",
  gruber_darker_niagara          = "#96a6c8",
  gruber_darker_wisteria         = "#9e95c7",
  gruber_darker_grey_custom      = "#7a7a7a",
  gruber_darker_green_custom     = "#369432",
  gruber_darker_green_custom_m1  = "#0a2517",
  gruber_darker_yellow_custom    = "#afa100",
  gruber_darker_yellow_custom_m1 = "#392a13",
  gruber_darker_red_custom       = "#960029",
  gruber_darker_red_custom_m1    = "#391a13",
  todo_fg                        = "#4ba8ff",
  todo_bg                        = "#0b1e33",
  note_fg                        = "#ff57fF",
  note_bg                        = "#1b0e23",
  warning_fg                     = "#ff9900",
  warning_bg                     = "#392a13",
  danger_fg                      = "#ff8b64",
  danger_bg                      = "#391a13",
}

return palette
