local palette = require('palette')
local main = palette.main
local text = palette.text
local diff = palette.diff
local diagnostic = palette.diagnostic
local git = palette.git
local telescope = palette.telescope

local highlight_groups = {
  --Main
  Normal                      = { bg = main.gruber_darker_bg, fg = main.gruber_darker_fg },
  Bold                        = { bold = true },
  Italic                      = { italic = true },
  -- Underlined                  = { underline = true },
  Visual                      = { bg = main.gruber_darker_bg_p3, fg = main.gruber_darker_fg },
  Directory                   = { fg = main.gruber_darker_quartz, bold = true },
  IncSearch                   = { fg = main.gruber_darker_fg_1, bg = main.gruber_darker_niagara_m1 },
  Search                      = { link = "IncSearch" },
  Substitute                  = { link = "IncSearch" },
  MatchParen                  = { fg = "", bg = main.gruber_darker_bg_p4 },
  ModeMsg                     = { link = "Normal" },
  MoreMsg                     = { link = "Normal" },
  WarningMsg                  = { fg = main.gruber_darker_yellow },
  FloatBorder                 = { fg = main.gruber_darker_grey_custom, bg = "" },
  NonText                     = { link = "Normal" },
  LineNr                      = { bg = main.gruber_darker_bg, fg = main.gruber_darker_grey_custom },
  LineNrAbove                 = { link = "LineNr" },
  LineNrBelow                 = { link = "LineNr" },
  CursorLineNr                = { fg = main.gruber_darker_yellow, bg = main.gruber_darker_bg },
  StatusLine                  = { fg = main.gruber_darker_quartz, bg = main.gruber_darker_bg_p1 },
  StatusLineNC                = { link = "StatusLine" },
  WinSeparator                = { fg = main.gruber_darker_grey_custom, bg = "" },
  SignColumn                  = { bg = main.gruber_darker_bg },
  Colorcolumn                 = { link = "StatusLine" },
  TabLineFill                 = { fg = "", bg = "" },
  TabLine                     = { fg = "", bg = "" },
  TabLineSel                  = { fg = "", bg = "" },
  Pmenu                       = { link = "Normal" },
  PmenuSel                    = { bg = main.gruber_darker_niagara_m2 },
  PmenuThumb                  = { bg = main.gruber_darker_bg_p3 },
  PmenuSbar                   = { link = "PmenuThumb" },
  Conceal                     = { link = "Operator" },
  Title                       = { link = "Normal" },
  Question                    = { link = "Normal" },
  WildMenu                    = { link = "Pmenu" },
  Folded                      = { fg = main.gruber_darker_grey_custom },
  FoldColumn                  = { link = "Folded" },
  Error                       = { fg = main.gruber_darker_red },
  ErrorMsg                    = { link = "Error" },
  -- Spelling
  SpellBad                    = { underline = true },
  SpellLocal                  = { underline = true },
  SpellCap                    = { underline = true },
  SpellRare                   = { underline = true },
  -- Syntax
  Boolean                     = { link = "String" },
  Character                   = { link = "Normal" },
  Comment                     = { fg = main.gruber_darker_grey_custom, italic = true },
  Conditional                 = { link = "Keyword" },
  Constant                    = { link = "Type" },
  Define                      = { link = "Keyword" },
  Delimiter                   = { link = "Special" },
  Float                       = { link = "Number" },
  Function                    = { fg = main.gruber_darker_niagara },
  Identifier                  = { fg = main.gruber_darker_fg_1 },
  Include                     = { link = "PreProc" },
  Keyword                     = { main.gruber_darker_yellow, bold = true },
  Label                       = { link = "String" },
  Number                      = { link = "Identifier" },
  Operator                    = { link = "Variable" },
  PreProc                     = { fg = main.gruber_darker_quartz },
  Repeat                      = { link = "Keyword" },
  Special                     = { link = "Keyword" },
  SpecialChar                 = { link = "String" },
  SpecialComment              = { link = "SpecialChar" },
  SpecialKey                  = { fg = main.gruber_darker_grey_custom, bg = main.gruber_darker_bg },
  Statement                   = { link = "Type" },
  StorageClass                = { link = "Keyword" },
  String                      = { fg = main.gruber_darker_green },
  Structure                   = { link = "Type" },
  Tag                         = { link = "SpecialChar" },
  Todo                        = { fg = text.todo_fg, bg = text.todo_bg },
  Type                        = { fg = main.gruber_darker_quartz },
  Typedef                     = { link = "Type" },
  ["@text.todo"]              = { fg = "#4BA8FF", bg = "#0b1e33" },
  ["@text.note"]              = { fg = "#FF57FF", bg = "#1b0e23" },
  ["@text.warning"]           = { fg = "#FF9900", bg = "#392a13" },
  ["@text.danger"]            = { fg = "#FF8B64", bg = "#391a13" },
  ["@text.uri"]               = { fg = main.gruber_darker_niagara, underline = true },
  ["@unchecked_list_item"]    = { link = "Normal" },
  ["@checked_list_item"]      = { fg = main.gruber_darker_grey_custom, strikethrough = true },
  ["@text.todo.unchecked"]    = { link = "@unchecked_list_item" },
  ["@text.todo.checked"]      = { link = "@checked_list_item" },
  ["@keyword"]                = { link = "Keyword" },
  ["@function"]               = { link = "Function" },
  ["@method"]                 = { link = "Function" },
  ["@field"]                  = { link = "Identifier" },
  ["@constructor"]            = { link = "Function" },
  ["@repeat"]                 = { link = "Repeat" },
  ["@label"]                  = { link = "String" },
  ["@variable"]               = { link = "Variable" },
  ["@type"]                   = { link = "Type" },
  ["@type.builtin"]           = { link = "Keyword" },
  ["@constant"]               = { link = "Type" },
  ["@variable.builtin"]       = { link = "Type" },
  ["@operator"]               = { link = "Variable" },
  ["@punctuation.special"]    = { link = "SpecialChar" },
  ["@punctuation.bracket"]    = { link = "Normal" },
  ["@conditional"]            = { link = "Conditional" },
  ["@exception"]              = { link = "Exception" },
  -- Diff
  DiffAdd                     = { fg = diff.add_fg, bg = diff.add_bg },
  DiffAdded                   = { fg = diff.added_fg, bg = diff.added_bg },
  DiffDelete                  = { fg = diff.delete_fg, bg = diff.delete_bg },
  DiffRemoved                 = { fg = diff.removed_fg, diff.removed_bg },
  DiffChange                  = { fg = diff.change_fg, bg = diff.change_bg },
  DiffText                    = { fg = diff.text_fg, bg = diff.text_bg, bold = true },
  DiffLine                    = { fg = diff.line_fg },
  -- Telescope
  TelescopeSelection          = { bg = telescope.selection_bg },
  TelescopeSelectionSelection = { link = "TelescopeSelection" },
  TelescopeMatching           = { fg = telescope.matching_fg, bold = true },
  --Git
  GitSignsAdd                 = { fg = git.sign_add_fg, bg = git.sign_add_bg },
  GitSignsChange              = { fg = git.sign_change_fg, bg = git.sign_change_bg },
  GitSignsDelete              = { fg = git.sign_delete_fg, bg = git.sign_delete_bg },
  --Diagnostic
  DiagnosticSignError         = { fg = diagnostic.error_fg, bg = diagnostic.error_bg },
  DiagnosticSignWarn          = { fg = diagnostic.warn_fg, bg = diagnostic.warn_bg },
  DiagnosticSignHint          = { fg = diagnostic.hint_fg, bg = diagnostic.hint_bg },
  DiagnosticSignInfo          = { fg = diagnostic.info_fg, bg = diagnostic.info_fg },
  DiagnosticError             = { link = "DiagnosticSignError" },
  DiagnosticWarn              = { link = "DiagnosticSignWarn" },
  DiagnosticHint              = { link = "DiagnosticSignHint" },
  DiagnosticInfo              = { link = "DiagnosticSignInfo" },
  --TODO Languages
  -- vim.api.nvim_set_hl(0, "@css.property_name", { fg = Gray_color })
  -- vim.api.nvim_set_hl(0, "@c.primitive_type", { link = "@type" })
  -- vim.api.nvim_set_hl(0, "@c.function_identifier", { link = "@variable" })

  --Scheme icon
  DevIconScheme               = { fg = main.gruber_darker_red },
  --Oil
  OilDir                      = { link = "Directory" },
  --Mason
  MasonHeader                 = { link = "StatusLine" },
}

return highlight_groups
